services:
  react-app:
    image: fe_service_conva:1.0
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.conva-fe.loadbalancer.server.port=80
      - traefik.http.routers.conva-fe-http.service=conva-fe
      - traefik.http.routers.conva-fe-http.entrypoints=http
      - traefik.http.routers.conva-fe-http.rule=Host(`${FE_DOMAIN}`)
      - traefik.http.routers.conva-fe-http.middlewares=https-redirect
      - traefik.http.routers.conva-fe-https.rule=Host(`${FE_DOMAIN}`)
      - traefik.http.routers.conva-fe-https.entrypoints=https
      - traefik.http.routers.conva-fe-https.tls=true
      - traefik.http.routers.conva-fe-https.service=go-service
      - traefik.http.routers.conva-fe-https.tls.certresolver=le
      - traefik.http.middlewares.fe-serviceheaders.headers.accesscontrolalloworiginlist=*
      - traefik.http.routers.conva-fe-http.middlewares=fe-serviceheaders
      - traefik.http.routers.conva-fe-https.middlewares=fe-serviceheaders
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true